### ISSUE TITLE
User password not correct in edit form/user cant login 

### ISSUE THREAD

**Issue by demon326** [llaumgui/ipb-for-drupal#2]
I found a new bug, so i just report it:

When a user is in the /user/<id>/edit screen and it tries to fill in the **current password** it says password incorrect, but the user just logged in with the same password.  This is on the drupal side. I think this is because drupal does **not** use MD5 for passwords and uses MD5 in combination with a salt...  Maybe you should have a look at this function: http://api.drupal.org/api/drupal/includes!password.inc/function/user_hash_password/7 

A other strange bug that was reported by a user is that he can't log in(this is not effecting every user, random users), its gives no error what so ever, the only thing giving away that something is wrong is the fact that there is a red border around the username field..  The above bugs are produceable by chaning the password of a user that has not logged in for a while and try it out...

If these three bugs reported by me should get fixed, it would be a very great module!

**Comment by llaumgui** [comment]
This project is deprecated, full rewrite planned with Drupal 8.
